### ISSUE TITLE
Camino Suite Account login with "ENTER"

### ISSUE THREAD

**Issue by vovanovaque** [chain4travel/camino-public-issues#1]
**Component**
Camino Suite login page

**Describe the new feature**
One-click login 

**Expected behavior**
When I enter my password, I press ENTER on my keyboard, but it doesn't work. Instead, I have to use the cursor to click "ACCESS WALLET". 

**Way of implementation**
Don't know 

**Pull request**
If applicable, write the number or the link to the PR.

**Screenshots**

**Operating System**
Mac OS

**Additional context**
It is a minor thing, but it makes the experience smoother.

**Comment by Noctunus** [comment]
Thanks for the suggestion!
We'll add this functionality in an upcoming suite release.

Devs: Please add a listener to the account login similar to the private key login that if you hit enter  you'll continue the login process.

**Comment by mo-c4t** [comment]
tested and worked on dev
