### ISSUE TITLE
UX on Camino Suite Partners

### ISSUE THREAD

**Issue by vovanovaque** [chain4travel/camino-public-issues#7]
**Component**
UX on Camino Suite Partners

**Describe the Bug**
When you open a page of a partner and swipe on touchpd right to come back to the overview of the partners, you arrive on the Suite page, not on the the list of partners. 

**Steps to Reproduce**

**Expected Behavior**
It would be more comfortable to swipe “back” and to arrive on the list of all partners.

**Screenshots**

<img width="1592" alt="Screenshot 2024-04-03 at 14 50 16" src="https://github.com/chain4travel/camino-public-issues/assets/108511295/971ef5a2-b4bc-4dd5-bca8-17dc75f8131f">

<img width="1295" alt="Screenshot 2024-04-03 at 14 50 21" src="https://github.com/chain4travel/camino-public-issues/assets/108511295/7400fca4-46fb-4464-ac5b-8c6b378bf35a">

**Comment by mo-c4t** [comment]
This is fixed in Suite v1.5.0
